(() => {
  const entry = (
    id,
    lesson,
    category,
    bisaya,
    english,
    pronunciation,
    tts
  ) => ({
    id,
    lesson,
    category,
    bisaya,
    english,
    pronunciation,
    tts,
    audio: `audio/${id}.wav`,
  });

  const lessonCatalog = [
    {
      id: "Lesson 01 · Core words",
      shortTitle: "Core words",
      summary: "Yes, no, thanks, please, and take care.",
    },
    {
      id: "Lesson 02 · Greetings",
      shortTitle: "Greetings",
      summary: "Morning, evening, and simple check-ins.",
    },
    {
      id: "Lesson 03 · Introduce yourself",
      shortTitle: "Introduce yourself",
      summary: "Names, where you are from, and warm intros.",
    },
    {
      id: "Lesson 04 · Question words",
      shortTitle: "Question words",
      summary: "What, where, who, when, and why.",
    },
    {
      id: "Lesson 05 · Feelings",
      shortTitle: "Feelings",
      summary: "Hungry, tired, thirsty, happy, and missing someone.",
    },
    {
      id: "Lesson 06 · Useful verbs",
      shortTitle: "Useful verbs",
      summary: "Eat, drink, go, come, wait, and watch.",
    },
    {
      id: "Lesson 07 · Simple actions",
      shortTitle: "Simple actions",
      summary: "Build short everyday actions and plans.",
    },
    {
      id: "Lesson 08 · Time words",
      shortTitle: "Time words",
      summary: "Now, later, tomorrow, and yesterday.",
    },
    {
      id: "Lesson 09 · Plans and meeting",
      shortTitle: "Plans",
      summary: "Make plans, ask availability, and meet up.",
    },
    {
      id: "Lesson 10 · Numbers 1 to 5",
      shortTitle: "Numbers",
      summary: "Learn the first basic numbers for daily use.",
    },
    {
      id: "Lesson 11 · Buying and prices",
      shortTitle: "Buying and prices",
      summary: "Ask costs, fares, and whether something is expensive.",
    },
    {
      id: "Lesson 12 · Travel around Cebu",
      shortTitle: "Travel around Cebu",
      summary: "Taxi, hotel, bathroom, and transport phrases.",
    },
    {
      id: "Lesson 13 · Food and restaurants",
      shortTitle: "Food and restaurants",
      summary: "Order, ask for water, and talk about taste.",
    },
    {
      id: "Lesson 14 · Places and location",
      shortTitle: "Places and location",
      summary: "Here, there, near, far, home, and city.",
    },
    {
      id: "Lesson 15 · Natural chat patterns",
      shortTitle: "Natural chat",
      summary: "Sound softer and more natural in conversation.",
    },
    {
      id: "Lesson 16 · Negatives and not yet",
      shortTitle: "Negatives",
      summary: "Not, not yet, already, and just now.",
    },
    {
      id: "Lesson 17 · Sweet phrases",
      shortTitle: "Sweet phrases",
      summary: "Like, love, and affectionate relationship chat.",
    },
    {
      id: "Lesson 18 · Compliments",
      shortTitle: "Compliments",
      summary: "Kind, beautiful, handsome, and smile compliments.",
    },
    {
      id: "Lesson 19 · Caring messages",
      shortTitle: "Caring messages",
      summary: "Eat well, rest, take care, and message later.",
    },
    {
      id: "Lesson 20 · Real chat practice",
      shortTitle: "Real chat practice",
      summary: "Useful voice-call and chat phrases for real moments.",
    },
  ];

  window.lessonCatalog = lessonCatalog;
  window.lessonEntries = [
    entry("oo", "Lesson 01 · Core words", "Basics", "Oo", "Yes", "oh-OH", "oh oh"),
    entry("dili", "Lesson 01 · Core words", "Basics", "Dili", "No", "dih-LEE", "dih lee"),
    entry("sige", "Lesson 01 · Core words", "Basics", "Sige", "Okay / Sure", "SEE-geh", "see geh"),
    entry("salamat", "Lesson 01 · Core words", "Basics", "Salamat", "Thank you", "sah-LAH-mat", "sah LAH mat"),
    entry("palihug", "Lesson 01 · Core words", "Basics", "Palihug", "Please", "pah-LEE-hoog", "pah LEE hoog"),
    entry("amping", "Lesson 01 · Core words", "Basics", "Amping", "Take care", "ahm-PING", "ahm PING"),

    entry("maayong-buntag", "Lesson 02 · Greetings", "Basics", "Maayong buntag", "Good morning", "mah-AH-yong BOON-tag", "mah AH yong boon tag"),
    entry("maayong-hapon", "Lesson 02 · Greetings", "Basics", "Maayong hapon", "Good afternoon", "mah-AH-yong HAH-pon", "mah AH yong HAH pon"),
    entry("maayong-gabii", "Lesson 02 · Greetings", "Basics", "Maayong gabii", "Good evening", "mah-AH-yong gah-BEE-ee", "mah AH yong gah BEE ee"),
    entry("kumusta-ka", "Lesson 02 · Greetings", "Basics", "Kumusta ka?", "How are you?", "koo-MOOS-tah kah", "koo MOOS tah kah"),
    entry("okay-ra-ko", "Lesson 02 · Greetings", "Basics", "Okay ra ko", "I am okay", "oh-KAI rah koh", "oh KAI rah koh"),
    entry("okay-ra-pud", "Lesson 02 · Greetings", "Basics", "Okay ra pud", "I am okay too", "oh-KAI rah pood", "oh KAI rah pood"),

    entry("akong-ngalan", "Lesson 03 · Introduce yourself", "Basics", "Akong ngalan kay ...", "My name is ...", "ah-KONG nga-LAN kai", "ah KONG nga LAN kai"),
    entry("taga-netherlands-ko", "Lesson 03 · Introduce yourself", "Basics", "Taga Netherlands ko", "I am from the Netherlands", "TAH-gah NE-ther-lands koh", "TAH gah nether lands koh"),
    entry("nalipay-ko-nga-nagkita-ta", "Lesson 03 · Introduce yourself", "Basics", "Nalipay ko nga nagkita ta", "I am happy we met", "nah-lih-PAI koh ngah nag-kee-TAH tah", "nah lih PAI koh ngah nag kee TAH tah"),
    entry("ikaw", "Lesson 03 · Introduce yourself", "Basics", "Ikaw?", "And you?", "ee-KAW", "ee KAW"),
    entry("taga-dinhi-ko", "Lesson 03 · Introduce yourself", "Basics", "Taga dinhi ko", "I am from here", "TAH-gah din-HEE koh", "TAH gah din HEE koh"),

    entry("unsa-ni", "Lesson 04 · Question words", "Basics", "Unsa ni?", "What is this?", "OON-sah nee", "OON sah nee"),
    entry("asa-ka", "Lesson 04 · Question words", "Basics", "Asa ka?", "Where are you?", "AH-sah kah", "AH sah kah"),
    entry("asa-ta-padulong", "Lesson 04 · Question words", "Basics", "Asa ta padulong?", "Where are we going?", "AH-sah tah pah-doo-LONG", "AH sah tah pah doo LONG"),
    entry("kinsa-na", "Lesson 04 · Question words", "Basics", "Kinsa na?", "Who is that?", "KIN-sah nah", "KIN sah nah"),
    entry("kanus-a", "Lesson 04 · Question words", "Basics", "Kanus-a?", "When?", "kah-NOOS-ah", "kah NOOS ah"),
    entry("ngano", "Lesson 04 · Question words", "Basics", "Ngano?", "Why?", "ngah-NOH", "ngah NOH"),

    entry("happy-ko", "Lesson 05 · Feelings", "Conversation", "Happy ko", "I am happy", "HAP-pee koh", "HAP pee koh"),
    entry("kapoy-ko", "Lesson 05 · Feelings", "Conversation", "Kapoy ko", "I am tired", "kah-POI koh", "kah POI koh"),
    entry("gutom-ko", "Lesson 05 · Feelings", "Conversation", "Gutom ko", "I am hungry", "goo-TOM koh", "goo TOM koh"),
    entry("uhaw-ko", "Lesson 05 · Feelings", "Conversation", "Uhaw ko", "I am thirsty", "oo-HAW koh", "oo HAW koh"),
    entry("gimingaw-ko-nimo", "Lesson 05 · Feelings", "Conversation", "Gimingaw ko nimo", "I miss you", "gih-mih-NGAW koh NEE-moh", "gih mih NGAW koh NEE moh"),

    entry("kaon", "Lesson 06 · Useful verbs", "Conversation", "Kaon", "Eat", "KAH-on", "KAH on"),
    entry("inom", "Lesson 06 · Useful verbs", "Conversation", "Inom", "Drink", "EE-nom", "EE nom"),
    entry("adto", "Lesson 06 · Useful verbs", "Conversation", "Adto", "Go", "AD-toh", "AD toh"),
    entry("anhi", "Lesson 06 · Useful verbs", "Conversation", "Anhi", "Come here", "AHN-hee", "AHN hee"),
    entry("hulat", "Lesson 06 · Useful verbs", "Conversation", "Hulat", "Wait", "HOO-lat", "HOO lat"),
    entry("tan-aw", "Lesson 06 · Useful verbs", "Conversation", "Tan-aw", "Look / watch", "tahn-AW", "tahn AW"),

    entry("mokaon-ko", "Lesson 07 · Simple actions", "Conversation", "Mokaon ko", "I will eat", "moh-KA-on koh", "moh KAH on koh"),
    entry("moinom-ko-ug-tubig", "Lesson 07 · Simple actions", "Conversation", "Moinom ko ug tubig", "I will drink water", "moh-EE-nom koh oog TOO-big", "moh EE nom koh oog TOO big"),
    entry("moadto-ko-ugma", "Lesson 07 · Simple actions", "Conversation", "Moadto ko ugma", "I will go tomorrow", "moh-AD-toh koh oog-MAH", "moh AD toh koh oog MAH"),
    entry("mokaon-ta", "Lesson 07 · Simple actions", "Conversation", "Mokaon ta", "Let us eat", "moh-KA-on tah", "moh KAH on tah"),
    entry("motext-ko-nimo-unya", "Lesson 07 · Simple actions", "Conversation", "Motext ko nimo unya", "I will text you later", "moh-TEKST koh NEE-moh OON-yah", "moh TEKST koh NEE moh OON yah"),

    entry("karon", "Lesson 08 · Time words", "Conversation", "Karon", "Now", "kah-RON", "kah RON"),
    entry("unya", "Lesson 08 · Time words", "Conversation", "Unya", "Later", "OON-yah", "OON yah"),
    entry("ugma", "Lesson 08 · Time words", "Conversation", "Ugma", "Tomorrow", "oog-MAH", "oog MAH"),
    entry("kagahapon", "Lesson 08 · Time words", "Conversation", "Kagahapon", "Yesterday", "kah-gah-HAH-pon", "kah gah HAH pon"),
    entry("karon-buntag", "Lesson 08 · Time words", "Conversation", "Karon buntag", "This morning", "kah-RON BOON-tag", "kah RON BOON tag"),
    entry("karong-gabii", "Lesson 08 · Time words", "Conversation", "Karong gabii", "Tonight", "kah-RONG gah-BEE-ee", "kah RONG gah BEE ee"),

    entry("magkita-ta-ugma", "Lesson 09 · Plans and meeting", "Conversation", "Magkita ta ugma", "Let us meet tomorrow", "mag-KEE-tah tah oog-MAH", "mag KEE tah tah oog MAH"),
    entry("libre-ka-ugma", "Lesson 09 · Plans and meeting", "Conversation", "Libre ka ugma?", "Are you free tomorrow?", "LEE-breh kah oog-MAH", "LEE breh kah oog MAH"),
    entry("tawag-ko-nimo-karong-gabii", "Lesson 09 · Plans and meeting", "Conversation", "Tawag ko nimo karong gabii", "I will call you tonight", "TAH-wag koh NEE-moh kah-RONG gah-BEE-ee", "TAH wag koh NEE moh kah RONG gah BEE ee"),
    entry("gusto-ko-makigkita-nimo", "Lesson 09 · Plans and meeting", "Conversation", "Gusto ko makigkita nimo", "I want to meet you", "GOOS-toh koh mah-kig-KEE-tah NEE-moh", "GOOS toh koh mah kig KEE tah NEE moh"),
    entry("wala-pa-ko-kabalo", "Lesson 09 · Plans and meeting", "Conversation", "Wala pa ko kabalo", "I do not know yet", "wah-LAH pah koh kah-bah-LOH", "wah LAH pah koh kah bah LOH"),

    entry("usa", "Lesson 10 · Numbers 1 to 5", "Travel", "Usa", "One", "oo-SAH", "oo SAH"),
    entry("duha", "Lesson 10 · Numbers 1 to 5", "Travel", "Duha", "Two", "doo-HA", "doo HA"),
    entry("tulo", "Lesson 10 · Numbers 1 to 5", "Travel", "Tulo", "Three", "too-LOH", "too LOH"),
    entry("upat", "Lesson 10 · Numbers 1 to 5", "Travel", "Upat", "Four", "oo-PAHT", "oo PAHT"),
    entry("lima", "Lesson 10 · Numbers 1 to 5", "Travel", "Lima", "Five", "LEE-mah", "LEE mah"),

    entry("tagpila-ni", "Lesson 11 · Buying and prices", "Travel", "Tagpila ni?", "How much is this?", "tag-PEE-lah nee", "tag PEE lah nee"),
    entry("pila-tanan", "Lesson 11 · Buying and prices", "Travel", "Pila tanan?", "How much is everything?", "PEE-lah tah-NAHN", "PEE lah tah NAHN"),
    entry("pila-ang-plete", "Lesson 11 · Buying and prices", "Travel", "Pila ang plete?", "How much is the fare?", "PEE-lah ang PLEH-teh", "PEE lah ang PLEH teh"),
    entry("mahal-ba", "Lesson 11 · Buying and prices", "Travel", "Mahal ba?", "Is it expensive?", "mah-HAL bah", "mah HAL bah"),
    entry("barato-ra", "Lesson 11 · Buying and prices", "Travel", "Barato ra", "It is cheap", "bah-RAH-toh rah", "bah RAH toh rah"),

    entry("asa-ni-padulong", "Lesson 12 · Travel around Cebu", "Travel", "Asa ni padulong?", "Where does this go?", "AH-sah nee pah-doo-LONG", "AH sah nee pah doo LONG"),
    entry("asa-ang-taxi", "Lesson 12 · Travel around Cebu", "Travel", "Asa ang taxi?", "Where is the taxi?", "AH-sah ang TAK-see", "AH sah ang TAK see"),
    entry("hunong-lang-diri", "Lesson 12 · Travel around Cebu", "Travel", "Hunong lang diri", "Please stop here", "hoo-NONG lang dee-REE", "hoo NONG lang dee REE"),
    entry("asa-ang-hotel", "Lesson 12 · Travel around Cebu", "Travel", "Asa ang hotel?", "Where is the hotel?", "AH-sah ang hoh-TEL", "AH sah ang hoh TEL"),
    entry("asa-ang-cr", "Lesson 12 · Travel around Cebu", "Travel", "Asa ang CR?", "Where is the bathroom?", "AH-sah ang see-AR", "AH sah ang see AR"),

    entry("lami-kaayo", "Lesson 13 · Food and restaurants", "Travel", "Lami kaayo", "Very delicious", "lah-MEE kah-AH-yoh", "lah MEE kah AH yoh"),
    entry("tubig-palihug", "Lesson 13 · Food and restaurants", "Travel", "Tubig, palihug", "Water, please", "TOO-big pah-LEE-hoog", "TOO big pah LEE hoog"),
    entry("pwede-mag-order", "Lesson 13 · Food and restaurants", "Travel", "Pwede mag-order?", "Can I order?", "PWEH-deh mag-OR-der", "PWEH deh mag OR der"),
    entry("kuhaon-nako", "Lesson 13 · Food and restaurants", "Travel", "Sige, kuhaon nako", "Okay, I will take it", "SEE-geh koo-HA-on nah-KOH", "SEE geh koo HAH on nah KOH"),
    entry("pwede-usab", "Lesson 13 · Food and restaurants", "Travel", "Pwede usab?", "Can you repeat that?", "PWEH-deh oo-SAB", "PWEH deh oo SAB"),

    entry("diri", "Lesson 14 · Places and location", "Travel", "Diri", "Here", "dee-REE", "dee REE"),
    entry("didto", "Lesson 14 · Places and location", "Travel", "Didto", "There", "deed-TOH", "deed TOH"),
    entry("duol", "Lesson 14 · Places and location", "Travel", "Duol", "Near", "doo-OL", "doo OL"),
    entry("layo", "Lesson 14 · Places and location", "Travel", "Layo", "Far", "lah-YOH", "lah YOH"),
    entry("naa-ra-ko-sa-balay", "Lesson 14 · Places and location", "Travel", "Naa ra ko sa balay", "I am just at home", "nah-AH rah koh sah bah-LAI", "nah AH rah koh sah bah LAI"),
    entry("syudad", "Lesson 14 · Places and location", "Travel", "Syudad", "City", "syoo-DAD", "syoo DAD"),

    entry("okay-ra-ba-ka", "Lesson 15 · Natural chat patterns", "Grammar", "Okay ra ba ka?", "Are you okay?", "oh-KAI rah bah kah", "oh KAI rah bah kah"),
    entry("diri-lang-sa", "Lesson 15 · Natural chat patterns", "Grammar", "Diri lang sa", "Just here for now", "dee-REE lang sah", "dee REE lang sah"),
    entry("ikaw-pud", "Lesson 15 · Natural chat patterns", "Grammar", "Ikaw pud", "You too", "ee-KAW pood", "ee KAW pood"),
    entry("gimingaw-gud-ko-nimo", "Lesson 15 · Natural chat patterns", "Grammar", "Gimingaw gud ko nimo", "I really miss you", "gih-mih-NGAW good koh NEE-moh", "gih mih NGAW good koh NEE moh"),
    entry("duol-ra-ba", "Lesson 15 · Natural chat patterns", "Grammar", "Duol ra ba?", "Is it near?", "doo-OL rah bah", "doo OL rah bah"),

    entry("dili-ko-kabalo", "Lesson 16 · Negatives and not yet", "Grammar", "Dili ko kabalo", "I do not know", "dih-LEE koh kah-bah-LOH", "dih LEE koh kah bah LOH"),
    entry("dili-ko-kasabot", "Lesson 16 · Negatives and not yet", "Grammar", "Dili ko kasabot", "I do not understand", "dih-LEE koh kah-sah-BOT", "dih LEE koh kah sah BOT"),
    entry("dili-lang-sa", "Lesson 16 · Negatives and not yet", "Grammar", "Dili lang sa", "Not for now", "dih-LEE lang sah", "dih LEE lang sah"),
    entry("naa-na-ka-sa-balay", "Lesson 16 · Negatives and not yet", "Grammar", "Naa na ka sa balay?", "Are you home already?", "nah-AH nah kah sah bah-LAI", "nah AH nah kah sah bah LAI"),
    entry("karon-pa-ko-nakaon", "Lesson 16 · Negatives and not yet", "Grammar", "Karon pa ko nakaon", "I only just ate now", "kah-RON pah koh nah-KA-on", "kah RON pah koh nah KAH on"),

    entry("ganahan-ko-nimo", "Lesson 17 · Sweet phrases", "Romance", "Ganahan ko nimo", "I like you", "gah-NA-han koh NEE-moh", "gah NA han koh NEE moh"),
    entry("palangga-tika", "Lesson 17 · Sweet phrases", "Romance", "Palangga tika", "I love you", "pah-LANG-ga tee-KAH", "pah LANG gah tee KAH"),
    entry("ganahan-kaayo-ko-nimo", "Lesson 17 · Sweet phrases", "Romance", "Ganahan kaayo ko nimo", "I like you very much", "gah-NA-han kah-AH-yoh koh NEE-moh", "gah NA han kah AH yoh koh NEE moh"),
    entry("happy-ko-basta-kuyog-tika", "Lesson 17 · Sweet phrases", "Romance", "Happy ko basta kuyog tika", "I am happy when I am with you", "HAP-pee koh BAH-stah koo-YOG tee-KAH", "HAP pee koh BAH stah koo YOG tee KAH"),
    entry("miss-na-kaayo-tika", "Lesson 17 · Sweet phrases", "Romance", "Miss na kaayo tika", "I miss you so much", "miss nah kah-AH-yoh tee-KAH", "miss nah kah AH yoh tee KAH"),

    entry("gwapa-kaayo-ka", "Lesson 18 · Compliments", "Romance", "Gwapa kaayo ka", "You are very beautiful", "GWAH-pah kah-AH-yoh kah", "GWAH pah kah AH yoh kah"),
    entry("gwapo-kaayo-ka", "Lesson 18 · Compliments", "Romance", "Gwapo kaayo ka", "You are very handsome", "GWAH-poh kah-AH-yoh kah", "GWAH poh kah AH yoh kah"),
    entry("nindot-kaayo-imong-smile", "Lesson 18 · Compliments", "Romance", "Nindot kaayo imong smile", "Your smile is beautiful", "NIN-dot kah-AH-yoh EE-mong smile", "NIN dot kah AH yoh EE mong smile"),
    entry("buotan-kaayo-ka", "Lesson 18 · Compliments", "Romance", "Buotan kaayo ka", "You are very kind", "boo-OH-tan kah-AH-yoh kah", "boo OH tan kah AH yoh kah"),
    entry("lipay-ko-nga-naa-ka", "Lesson 18 · Compliments", "Romance", "Lipay ko nga naa ka", "I am happy that you are here", "lee-PAI koh ngah nah-AH kah", "lee PAI koh ngah nah AH kah"),

    entry("amping-pirmi-ha", "Lesson 19 · Caring messages", "Romance", "Amping pirmi, ha", "Always take care, okay?", "ahm-PING PEER-mee ha", "ahm PING PEER mee ha"),
    entry("kaon-tarong-ha", "Lesson 19 · Caring messages", "Romance", "Kaon tarong, ha", "Eat properly, okay?", "KAH-on tah-RONG ha", "KAH on tah RONG ha"),
    entry("pahuway-sad", "Lesson 19 · Caring messages", "Romance", "Pahuway sad", "Get some rest too", "pah-hoo-WAI sahd", "pah hoo WAI sahd"),
    entry("texti-ko-unya", "Lesson 19 · Caring messages", "Romance", "Texti ko unya", "Message me later", "TEKS-tee koh OON-yah", "TEKS tee koh OON yah"),
    entry("tawagi-ko-kung-free-ka", "Lesson 19 · Caring messages", "Romance", "Tawagi ko kung free ka", "Call me if you are free", "tah-WAH-ghee koh koong free kah", "tah WAH ghee koh koong free kah"),

    entry("asa-na-ka", "Lesson 20 · Real chat practice", "Romance", "Asa na ka?", "Where are you now?", "AH-sah nah kah", "AH sah nah kah"),
    entry("unsay-gibuhat-nimo", "Lesson 20 · Real chat practice", "Romance", "Unsay gibuhat nimo?", "What are you doing?", "OON-sai gih-boo-HAT NEE-moh", "OON sai gih boo HAT NEE moh"),
    entry("nakaon-na-ka", "Lesson 20 · Real chat practice", "Romance", "Nakaon na ka?", "Have you eaten already?", "nah-KA-on nah kah", "nah KAH on nah kah"),
    entry("matulog-na-ka", "Lesson 20 · Real chat practice", "Romance", "Matulog na ka?", "Are you going to sleep now?", "mah-too-LOG nah kah", "mah too LOG nah kah"),
    entry("nasabtan-nako-gamay", "Lesson 20 · Real chat practice", "Romance", "Nasabtan nako gamay", "I understand a little", "nah-sab-TAHN nah-KOH gah-MAI", "nah sab TAHN nah KOH gah MAI"),
    entry("nagtuon-pa-ko-ug-bisaya", "Lesson 20 · Real chat practice", "Romance", "Nagtuon pa ko ug Bisaya", "I am still learning Bisaya", "nag-TOO-on pah koh oog bee-SAH-yah", "nag TOO on pah koh oog bee SAH yah"),
    entry("hinay-hinay-lang-palihug", "Lesson 20 · Real chat practice", "Romance", "Hinay-hinay lang palihug", "Please speak slowly", "hee-NAI hee-NAI lang pah-LEE-hoog", "hee NAI hee NAI lang pah LEE hoog"),
    entry("nalipay-ko-nga-nakastorya-tika", "Lesson 20 · Real chat practice", "Romance", "Nalipay ko nga nakastorya tika", "I am happy that I got to talk to you", "nah-lih-PAI koh ngah nah-kah-STOR-yah tee-KAH", "nah lih PAI koh ngah nah kah STOR yah tee KAH"),

    entry("salamat-kaayo", "Lesson 01 · Core words", "Basics", "Salamat kaayo", "Thank you very much", "sah-LAH-mat kah-AH-yoh", "sah LAH mat kah AH yoh"),
    entry("kumusta-ang-adlaw-nimo", "Lesson 02 · Greetings", "Basics", "Kumusta ang adlaw nimo?", "How was your day?", "koo-MOOS-tah ang AD-law NEE-moh", "koo MOOS tah ang AD law NEE moh"),
    entry("nalipay-ko-makaila-ka", "Lesson 03 · Introduce yourself", "Conversation", "Nalipay ko makaila ka", "Nice to meet you", "nah-lih-PAI koh mah-kai-LAH kah", "nah lih PAI koh mah kai LAH kah"),
    entry("kanus-a-ta-magkita", "Lesson 04 · Question words", "Conversation", "Kanus-a ta magkita?", "When shall we meet?", "kah-NOOS-ah tah mag-kee-TAH", "kah NOOS ah tah mag kee TAH"),
    entry("kapoy-gamay-ko-karon", "Lesson 05 · Feelings", "Conversation", "Kapoy gamay ko karon", "I am a little tired now", "kah-POI gah-MAI koh kah-RON", "kah POI gah MAI koh kah RON"),
    entry("mohulat-ko-diri", "Lesson 06 · Useful verbs", "Conversation", "Mohulat ko diri", "I will wait here", "moh-HOO-lat koh dee-REE", "moh HOO lat koh dee REE"),
    entry("moadto-ko-sa-mall-ugma", "Lesson 07 · Simple actions", "Conversation", "Moadto ko sa mall ugma", "I will go to the mall tomorrow", "moh-AD-toh koh sah mall OOG-mah", "moh AD toh koh sah mall OOG mah"),
    entry("magstorya-ta-karon-gabii", "Lesson 08 · Time words", "Conversation", "Magstorya ta karon gabii", "Let's talk tonight", "mag-STOR-yah tah kah-RON gah-BEE-ee", "mag STOR yah tah kah RON gah BEE ee"),
    entry("pwede-ka-karong-gabii", "Lesson 09 · Plans and meeting", "Conversation", "Pwede ka karong gabii?", "Are you free tonight?", "PWEH-deh kah kah-RONG gah-BEE-ee", "PWEH deh kah kah RONG gah BEE ee"),
    entry("lima-ka-minutos-ra", "Lesson 10 · Numbers 1 to 5", "Travel", "Lima ka minutos ra", "Just five minutes", "LEE-mah kah mee-NOO-tos rah", "LEE mah kah mee NOO tos rah"),
    entry("naa-bay-mas-barato", "Lesson 11 · Buying and prices", "Travel", "Naa bay mas barato?", "Is there a cheaper one?", "nah-AH bai mahs bah-RAH-toh", "nah AH bai mahs bah RAH toh"),
    entry("dad-a-ko-sa-ayala", "Lesson 12 · Travel around Cebu", "Travel", "Dad-a ko sa Ayala", "Take me to Ayala", "dahd-AH koh sah ai-YAH-lah", "dahd AH koh sah ai YAH lah"),
    entry("lami-kaayo-ang-pagkaon", "Lesson 13 · Food and restaurants", "Travel", "Lami kaayo ang pagkaon", "The food is very delicious", "lah-MEE kah-AH-yoh ang pag-kah-ON", "lah MEE kah AH yoh ang pag kah ON"),
    entry("asa-ta-magkita", "Lesson 14 · Places and location", "Travel", "Asa ta magkita?", "Where shall we meet?", "AH-sah tah mag-kee-TAH", "AH sah tah mag kee TAH"),
    entry("okay-ra-ko-gamay-rag-kapoy", "Lesson 15 · Natural chat patterns", "Grammar", "Okay ra ko, gamay rag kapoy", "I am okay, just a little tired", "oh-KAI rah koh gah-MAI rag kah-POI", "oh KAI rah koh gah MAI rag kah POI"),
    entry("wala-pa-ko-kaabot", "Lesson 16 · Negatives and not yet", "Grammar", "Wala pa ko kaabot", "I have not arrived yet", "wah-LAH pah koh kah-AH-bot", "wah LAH pah koh kah AH bot"),
    entry("gusto-ko-makita-ka", "Lesson 17 · Sweet phrases", "Romance", "Gusto ko makita ka", "I want to see you", "GOOS-toh koh mah-kee-TAH kah", "GOOS toh koh mah kee TAH kah"),
    entry("ganahan-ko-sa-imong-smile", "Lesson 18 · Compliments", "Romance", "Ganahan ko sa imong smile", "I like your smile", "gah-NA-han koh sah EE-mong smile", "gah NA han koh sah EE mong smile"),
    entry("inom-ug-tubig-ha", "Lesson 19 · Caring messages", "Romance", "Inom ug tubig, ha", "Drink water, okay?", "EE-nom oog TOO-big ha", "EE nom oog TOO big ha"),
    entry("nakauli-na-ka", "Lesson 20 · Real chat practice", "Romance", "Nakauli na ka?", "Are you home already?", "nah-kah-OO-lee nah kah", "nah kah OO lee nah kah"),
  ];
})();
